export CLAS12RAD=$GITHUB_WORKSPACE
export RAD=$CLAS12RAD/rad
export ROOT_INCLUDE_PATH=$RAD/include:$CLAS12RAD/include:$ROOT_INCLUDE_PATH

echo "CLAS12RAD=$CLAS12RAD" | tee -a $GITHUB_ENV
echo "RAD=$RAD" | tee -a $GITHUB_ENV
echo "ROOT_INCLUDE_PATH=$ROOT_INCLUDE_PATH" | tee -a $GITHUB_ENV
